[tool.black]
line-length=120

[tool.poetry]
name = "aoa"
version = "0.1.0"
description = "Create activity on arrow diagrams from yaml input"
authors = ["David Stadelmann <david.stadelmann@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python =">=3.12,<3.14.1 || >3.14.1,<4.0"
flask = "^3.0.0"
flask-cors = "^5.0.0"
htmx = "^0.0.0"
more-itertools = "^10.1.0"
cattrs = "^25.3.0"
pyfakefs = "^5.10.2"
pytest-sugar = "^1.1.1"
drawsvg = "^2.4.1"
cairosvg = "^2.8.2"
numpy = "^2.4.1"
networkx = "^3.6.1"
pygraphviz = "^1.14"
matplotlib = "^3.10.8"
fast-sugiyama = "^0.5.2"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
isort = "^5.12.0"
debugpy = "^1.6.7.post1"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
